# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

index <- function(i, j, k, l, a, b, c, d) {
    .Call(`_INNMMD_index`, i, j, k, l, a, b, c, d)
}

PARAMETERS <- function(n, d, iteration) {
    .Call(`_INNMMD_PARAMETERS`, n, d, iteration)
}

INNMMDPRESET <- function(n, d, parameters) {
    .Call(`_INNMMD_INNMMDPRESET`, n, d, parameters)
}

MMD <- function(X, m, subpreset) {
    .Call(`_INNMMD_MMD`, X, m, subpreset)
}

INNMMD <- function(dlist, n, d, preset) {
    .Call(`_INNMMD_INNMMD`, dlist, n, d, preset)
}

INNMMDTEST <- function(D, n, d, preset, iteration) {
    .Call(`_INNMMD_INNMMDTEST`, D, n, d, preset, iteration)
}

